apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_DB: TW92aWU=             # Base64 encoded value of "Movie"
  POSTGRES_USER: d2FsaWQ=          # Base64 encoded value of "walid"
  POSTGRES_PASSWORD: V2FsaWQxMjM=  # Base64 encoded value of "Walid123" 